# simple-nginx/values.yaml
replicaCount: 1

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx" # Use "nginx" or "alb"
  host: my-app.local
  paths:
    - path: /
      pathType: Prefix
      servicePort: 80
